spring.application.name=rental_eventos

server.port=8080
spring.datasource.url=localhost
spring.datasource.username=postgres
spring.datasource.password=ALUNO
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/dobi-2/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true